---
- hosts: all
  gather_facts: false
  vars:
    store_directory: "/tmp"
    network_name: "infrastructure_default"
  tasks:
    - name: Clone repo and set server branch
      ansible.builtin.git:
        repo: https://github.com/FizzyShow/markershtern.git
        dest: "{{ store_directory }}/{{ SERVICE_NAME }}"
        version: "{{ SERVICE_BRANCH }}"
        force: true

    - name: Set workdir
      ansible.builtin.command:
        cmd: cd "{{ store_directory }}/{{ SERVICE_NAME }}"

    - name: Stop previous version
      ansible.builtin.command:
        cmd: "docker stop {{ SERVICE_NAME }}"
    
    - name: Remove previous version
      ansible.builtin.command:
        cmd: "docker rm {{ SERVICE_NAME }}"

    - name: Copy Dockerfile
      ansible.builtin.copy:
        src: ./Dockerfile
        dest: "{{ store_directory }}/Dockerfile"
        mode: 600
        owner: "{{ ansible_user_id }}"

    - name: Dockerize service
      ansible.builin.command:
        cmd: "docker build -t {{ SERVICE_NAME }} ."
      environment:
        SRC_PATH: "{{ SRC_PATH }}"
        SERVICE_NAME: "{{ SERVICE_NAME }}"

    - name: Run dockerized service
      ansible.builin.command:
        cmd: "docker run -d --network {{ network_name }} --publish {{ SERVICE_PORT }}:{{ SERVICE_PORT }} --name {{ SERVICE_NAME }}"
      environment:
        SRC_PATH: "{{ SRC_PATH }}"
        SERVICE_NAME: "{{ SERVICE_NAME }}"
...