version: "3"

services:
  zookeeper:
    image: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    networks:
      - kafka-network
    volumes:
      - zookeeper:/data
      - zookeeper:/datalog

  kafka:
    build: ./kafka
    restart: unless-stopped
    environment:
       ALLOW_PLAINTEXT_LISTENER: "yes"
       KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - "9092:9092"
    networks:
      - kafka-network
    volumes:
      - kafka:/bitnami/kafka

networks:
  kafka-network:
    driver: bridge

volumes:
  zookeeper:
  kafka:
