version: "3.9"

services:
  zookeeper:
    image: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    networks:
      - kafka-network
    volumes:
      - zookeeper-data:/data
      - zookeeper-datalog:/datalog
      - ./zookeeper/zoo.cfg:/conf/zoo.cfg:ro
    mem_limit: ${ZOO_MAX_MEM:-1024m}
    environment:
      JVMFLAGS: "-Xmx${ZOO_MAX_MEM:-1024m}"
      ZOO_MY_ID: 1

  kafka:
    build: ./kafka
    depends_on:
      - zookeeper
    restart: unless-stopped
    mem_limit: ${KAFKA_MAX_MEM:-1024m}
    environment:
      KAFKA_HEAP_OPTS: "-Xmx${KAFKA_MAX_MEM:-1024m} -Xms${KAFKA_MAX_MEM:-1024m}"
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_CFG_ZOOKEEPER_CONNECT: "zookeeper:2181"
    ports:
      - "9092:9092"
    networks:
      - kafka-network
    volumes:
      - kafka:/bitnami/kafka

networks:
  kafka-network:
    driver: bridge

volumes:
  zookeeper-data:
  zookeeper-datalog:
  kafka:
